
######################

PATCH   http://localhost:3001/users/user HTTP/1.1
content-type: application/json


{
    
    "email": "user@mail.com",
    "name": "newman",
    "hobbies": "playing games"

    
}
######################

get   http://localhost:3001/users/user HTTP/1.1
content-type: application/json



